# Generated by Django 4.0 on 2022-01-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_id_alter_image_id_alter_image_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Image_field',
        ),
    ]
