# Generated by Django 4.0 on 2022-01-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_image_image_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_field',
            new_name='Image',
        ),
    ]
