# Generated by Django 4.0 on 2022-01-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
